name: Build

on:
  push:
    branches: [ "main", "ndkbuild-18.12.1" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Environment Check
      run: |
        echo "BUILD_TYPE: $BUILD_TYPE"
    - name: Build Targets
      working-directory: ${{github.workspace}}
      run: .\vcbuild
